### PR TITLE
Testing branch

### PR DESCRIPTION
**Pull request by mohapakram**
This Branch contains our implementation of test cases for the following methods:

- my_each
- my_select
- my_inject
- my_map
- my_each_with_index
- my_none?
- my_count
- my_all?

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi Team. 👋

You seemed to have worked hard at this. 👍

However, let's fix these:

- [x] Please include in your readme a proper description of the project listing all the enumerable methods you worked on. Also, include instructions on how to run the tests.

- [x] Your tests aren't running. They throw an error: `LoadError: cannot load such file -- ../enumerables`. Please fix it.

- [x] Also please add negative scenarios in your tests. There are mostly positive scenarios please include corresponding negative scenarios also.

- [x] In addition, kindly use require_relative for files in your directory as it's a ruby convention.

- [x] Your GitHub workflows folder isn't properly setup please include tests.yml. Refer to [this link](https://github.com/microverseinc/linters-config/tree/master/ruby) for the proper setup.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by mohapakram** [comment]
As you can see the tests are running successfully when I run `rspec` in the terminal.
image

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for applying 
However, there are some issues

1. That code failed your tests
```rb
2.6.5 :009 > array
 => [1, 4, 3, 6, 5, 1, 8, 7, 2, 3, 8, 3, 6, 8, 0, 5, 0, 8, 0, 0, 4, 0, 5, 3, 0, 4, 2, 5, 4, 8, 6, 0, 1, 1, 6, 5, 4, 1, 4, 2, 4, 8, 7, 2, 8, 4, 6, 7, 4, 4, 1, 4, 1, 2, 7, 2, 2, 1, 2, 3, 1, 5, 8, 4, 0, 3, 4, 8, 3, 7, 0, 5, 8, 2, 3, 8, 5, 3, 7, 6, 7, 8, 3, 5, 8, 1, 5, 8, 8, 6, 5, 4, 2, 0, 2, 8, 3, 7, 4, 5] 
2.6.5 :010 > array.none?(String)
 => true 
2.6.5 :011 > array.my_none?(String)
 => true 
2.6.5 :012 > array[0] = 'hi'
2.6.5 :013 > array.none?(String)
 => false 
2.6.5 :014 > array.my_none?(String)
 => true 
2.6.5 :015 > 
```
Kindly, fix that

2. Please, for method like `my_all?`, `my_none?`, `my_any?`, can you write tests for **Regex**, **String or Integer** or another class (like example up there). 
Also add test, for true or false array. That is checking if a n array passes the test.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Comment by mohapakram** [comment]
Please Look at the code :) 
All the tests are passed and I have the true and false arrays .. also I've tested each function for the requirements mentioned in the docs for ruby : https://ruby-doc.org/core-2.7.1/Enumerable.html

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
### Hello Team :wave: 
### Status: Changes Required :recycle: 

Congratulations :clap:  All of your tests are passing :heavy_check_mark: :blush: 


And also we need to fulfill the requirements of this project. And one of them is :arrow_down: 
### [REQUIRED]
- [ ] All methods implemented in the Enumerables project are tested ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/all_enumerables.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/testing-your-ruby-code))
:bulb: As the previous TSE mentioned, please add tests for `multiply_els` and `my_none?` methods.

Thanks for your time and efforts.
With all my respect... :pray:

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Good job team. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job :+1:
- You can now merge these changes.
- I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
